#!/usr/bin/python
PLC_API_HOST='myplc.ict.ac.cn'
PLC_API_PATH='/PLCAPI/'
PLC_API_PORT='443'
PLC_WWW_HOST='myplc.ict.ac.cn'
PLC_BOOT_HOST='myplc.ict.ac.cn'
PLC_PLANETFLOW_HOST='localhost.localdomain'
PLC_NAME='CENI'
PLC_SLICE_PREFIX='CENI'
PLC_MONITOR_HOST='localhost.localdomain'
PLC_MAIL_SUPPORT_ADDRESS='wangyang2013@ict.ac.cn'
PLC_MAIL_MOM_LIST_ADDRESS='root+mom@localhost.localdomain'
PLC_MAIL_SLICE_ADDRESS='root+SLICE@localhost.localdomain'
PLC_API_CA_SSL_CRT='/usr/boot/cacert.pem'
PLC_ROOT_GPG_KEY_PUB='/usr/boot/pubring.gpg'

